version: '3.9'

services:
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: KRIStiNA01101985
    ports:
      - "5432:5432"
  
  redis:
    image: "redis:alpine"
  
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - REDIS_URL=redis://redis:6379/0
  
  celeryworker:
    build: .
    command: celery -A car_search_service worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - web
      - redis
  
  celerybeat:
    build: .
    command: celery -A car_search_service beat --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - web
      - redis

volumes:
  postgres_data:
